branches:
  only:
    - master
    - develop
    - /^hotfix.*$/
    - /^feature.*$/

notifications:
  email:
    on_success: change
    on_failure: always

osx_image: xcode9
language: swift

before_install:
  - pod repo update
  - carthage update

script: 
  - carthage build --no-skip-current
  - fastlane test
  - pod lib lint